site_name: Sparrow Albatros
theme:
  name: readthedocs
  highlightjs: true
  hljs_languages:
    - python
    - c
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: ["./software"]
          options:
            show_source: true
            show_root_heading: true
            heading_level: 5
            show_category_heading: false
            members_order: source
            inherited_members: false
            special_members: false
            docstring_style: google
  - mkdocs-jupyter:
      include: ["*.ipynb"]
      execute: false
      include_source: true
      include_requirejs: true  # Add this line - helps with rendering
extra_javascript:
  - wavedrom-init.js
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
markdown_extensions:
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.snippets:
      base_path: '.'
extra_css:
  - stylesheets/extra.css 
nav: 
  - Home: index.md
  - Embedded Software:
    - Run the DAQ, collect data: data-collection.md
    - Tuning the gateware: tuning-the-gateware.md
    - Optimal Digital Gain Coefficients (4-bit): digital-gain-coefficients-4bit.ipynb
    - Dumping baseband: dump-baseband.md
    - Dumping correlated spectra: dump-spectra.md
    - Networking: networking.md
  - Gateware:
    - Installing the Toolchain: installing-the-toolchain.md
    - Design Overview: gateware-design.md
    - Note on FFT Implementation: fft-note.md
    - Modify and Simulate: gateware-modify-simulate.md
    - Compile, Synthesize, Implement: gateware-compile-synthesize-implement.md
  - Disk Images:
    - Installing Sparrow Albatros: installing-sparrow-albatros.md
  - Data Specification:
    - Baseband: data-baseband.md
    - Correlated Spectra: data-correlated-spectra.md
