site_name: Sparrow Albatros
theme:
  name: readthedocs
  highlightjs: true
  hljs_languages:
    - python
    - c
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: ["./software"]
          options:
            show_source: true
            show_root_heading: true
            heading_level: 3
            show_category_heading: false
            members_order: source
            inherited_members: false
            special_members: false
            docstring_style: google
extra_javascript:
  - wavedrom-init.js
markdown_extensions:
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
extra_css:
  - stylesheets/extra.css 
nav: 
  - Home: index.md
  - Embedded Software:
    - Run the DAQ, collect data: data-collection.md
    - Tuning the gateware: tuning-the-gateware.md
  - Gateware:
    - Installing the Toolchain: installing-the-toolchain.md
    - Design Overview: gateware-design.md
    - Modify and Simulate: gateware-modify-simulate.md
    - Compile, Synthesize, Implement: gateware-compile-synthesize-implement.md
  - Disk Images:
    - Installing Sparrow Albatros: installing-sparrow-albatros.md
