site_name: Sparrow Albatros
theme:
  name: readthedocs
  highlightjs: true
  hljs_languages:
    - python
    - c
markdown_extensions:
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
extra_css:
  - stylesheets/extra.css 
nav: 
  - Home: index.md
  - Embedded Software:
    - Collecting data (quick start): collecting-data-quickstart.md
    - Collecting data (in depth): collecting-data-in-depth.md
  - Gateware:
    - Gateware overview: gateware-design.md
    - Installing the toolchain: installing-the-toolchain.md
    - Gateware: gateware-documentation.md
  - Disk Images:
    - Installing Sparrow Albatros: installing-sparrow-albatros.md
